on:
  schedule:
    - cron: '* * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
