name: NYT scheduler
on:
  workflow_dispatch:
  schedule:
    - cron: '36 4 * * *'
jobs:
  nyt:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: nyt
