name: Sync to S3
on:
  workflow_dispatch:
    inputs:
        site:
          description: site
          required: true
          default: 'nyt'
          type: string
jobs:
  brush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Sync to S3
      run: aws s3 cp README.md s3://epub-test-fixtures
    - name: Install dependencies
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10
      run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
