name: Working sites launcher 5
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 */2 * *'
jobs:
  Rochester_Business_Journal:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Rochester Business Journal
  Associated_Press_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Associated Press News
  KSTU:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KSTU
  Arvada_Press:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Arvada Press
  OneNewsNow:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: OneNewsNow
  Grand_Forks_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Grand Forks Herald
  KUSI:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KUSI
  La_Crosse_Tribune:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: La Crosse Tribune
  Rapzilla:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Rapzilla
  Literary_Hub:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Literary Hub
  KALW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KALW
  Action_News_5:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Action News 5
  Soldier_Systems_Daily:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Soldier Systems Daily
  KEVN_Black_Hills_Fox:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KEVN Black Hills Fox
  WhatTheyThink:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WhatTheyThink
  Southwest_Iowa_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Southwest Iowa News
  The_New_Civil_Rights_Movement:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The New Civil Rights Movement
  WAFB:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WAFB
  WTSP:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WTSP
  Hometown_News_Group_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Hometown News Group News
  Waste_Today:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Waste Today
  The_Eagle:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Eagle
  ungeek_ph:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ungeek.ph
  Palgrave_Macmillan:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Palgrave Macmillan
  Dancing_Astronaut:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Dancing Astronaut
  iFixit:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: iFixit
  Englewood:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Englewood
  The_Herald_Mail:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Herald-Mail
  KRGV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KRGV
  Sportsnaut:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sportsnaut
  KATC:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KATC
  FOX_17:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FOX 17
  The_Herald_Dispatch:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Herald-Dispatch
  Fox_12_Oregon:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Fox 12 Oregon
  KIRO_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KIRO-TV
  WGN_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WGN-TV
  WKAR:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WKAR
  BevIndustry:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: BevIndustry
  First_Coast_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: First Coast News
  Thehypemagazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Thehypemagazine
  The_Toy_Insider:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Toy Insider
  Republican_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Republican Herald
  Gillette_News_Record:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Gillette News Record
  WKYC3:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WKYC3
  Steelers_Depot:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Steelers Depot
  WBRC_FOX6_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WBRC FOX6 News
  Saturday_Tradition:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Saturday Tradition
  WKRG_News_5:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WKRG News 5
  Northwestern_Media:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Northwestern Media
  _49ers_Webzone:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 49ers Webzone
  Zenit_News_Agency:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Zenit News Agency
  Arizona_Daily_Sun:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Arizona Daily Sun
  Northwest_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Northwest Herald
  KVUE:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KVUE
  aha_org:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: aha.org
  MS_NEWS_NOW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: MS NEWS NOW
  Lehigh_Valley_Live:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Lehigh Valley Live
  The_Aquila_Report:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Aquila Report
  RotoBaller:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: RotoBaller
  Campaign_US:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Campaign US
  Scottsbluff_Star_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Scottsbluff Star Herald
  KIOW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KIOW
  The_Review:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Review
  cinespeaks_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: cinespeaks.com
  WAVE3:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WAVE3
  SD_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: SD Times
  The_Register_Guard:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Register-Guard
  Public_Opinion:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Public Opinion
  NBC_7_San_Diego:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: NBC 7 San Diego
  KHNL:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KHNL
  The_Journal_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Journal Times
  NBC_Connecticut:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: NBC Connecticut
  KIMT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KIMT
  Dazed:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Dazed
  Fr__Z:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Fr. Z
  Jamestown_Sun:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Jamestown Sun
  www_aljazeera_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: www.aljazeera.com
  Erie_Times_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Erie Times-News
  Mosaic_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Mosaic Magazine
  WWLP:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WWLP
  KSHB_Kansas_City:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KSHB Kansas City
  Clayton_Davis:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Clayton Davis
  KXLY_4_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KXLY 4 News
  WOFL:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WOFL
  Herald_Whig:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Herald Whig
  ANewsCafe:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ANewsCafe
  KWIT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KWIT
  The_Violin_Channel:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Violin Channel
  Kerrville_Daily_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Kerrville Daily Times
  _5_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 5 News
  Futurity_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Futurity News
  PCT_Online:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: PCT Online
  WWLTV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WWLTV
  NBC_10_Philadelphia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: NBC 10 Philadelphia
  University_of_Hawaii:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: University of Hawaii
  SciTech_Daily:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: SciTech Daily
  GovTrack:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: GovTrack
  Norfolk_Daily_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Norfolk Daily News
  KFLZ:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KFLZ
  Cherokee_Tribune:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Cherokee Tribune
  The_Christian_Post:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Christian Post
  Fox21_Online:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Fox21 Online
  The_Clemson_Insider:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Clemson Insider
  WKBW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WKBW
  National_Bureau_of_Economic_Research:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: National Bureau of Economic Research
  Tabletop_Gaming_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Tabletop Gaming News
  WJON:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WJON
  WABI:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WABI
  Rotten_Tomatoes:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Rotten Tomatoes
  A_Cup_of_Jo:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: A Cup of Jo
  Bike_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bike Magazine
  WXIX_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WXIX-TV
  The_Anderson_Independent_Mail:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Anderson Independent-Mail
  WSAW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WSAW
  Pulitzer_Center:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Pulitzer Center
  The_Kingdom_Insider:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Kingdom Insider
  WSFA:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WSFA
  The_Real_Deal:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Real Deal
  Wausau_Daily_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Wausau Daily Herald
  KERO_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KERO-TV
  Bartlesville_Radio:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bartlesville Radio
  FOX43:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FOX43
  FSView___Florida_Flambeau:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FSView & Florida Flambeau
  Inside_EVs:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Inside EVs
  Salisbury_Post:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Salisbury Post
  Sojo:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sojo
  NBC_6_South_Florida:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: NBC 6 South Florida
  MadameNoire:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: MadameNoire
  Valley_News_Live:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Valley News Live
  WFSU:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WFSU
  AZFamily:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AZFamily
  WGBH:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WGBH
  International_Christian_Concern:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: International Christian Concern
  WSJM:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WSJM
  Food_Network:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Food Network
  Richland_Source:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Richland Source
  The_AstroTwins:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The AstroTwins
  WTOC_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WTOC-TV
  Cleveland_Browns:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Cleveland Browns
  East_Idaho_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: East Idaho News
  WKXW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WKXW
  The_News___Advance:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The News & Advance
  Thurrott:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Thurrott
  Star_Democrat:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Star Democrat
  Centreforaviation_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Centreforaviation.com
  News_on_6:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: News on 6
  Argh_Ink:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Argh Ink
  WHEC:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WHEC
  World_Screen:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: World Screen
  FOX59_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FOX59 News
  Bring_Me_The_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bring Me The News
  TMJ4:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: TMJ4
  Fort_Collins_Coloradoan:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Fort Collins Coloradoan
  Public_Radio_East:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Public Radio East
  WMBF_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WMBF News
  Targeted_Oncology:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Targeted Oncology
  Real_Simple:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Real Simple
  Physics_Forums:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Physics Forums
  Motocross_Action_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Motocross Action Magazine
  CBS_News_8:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CBS News 8
  New_Hampshire_Public_Radio:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: New Hampshire Public Radio
  Alabama_Public_Radio:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Alabama Public Radio
  WLTX19:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WLTX19
  Brainerd_Dispatch:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Brainerd Dispatch
  Player_One:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Player.One
  Journal_Record:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Journal Record
  Times_of_San_Diego:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Times of San Diego
  Huron_Daily_Tribune:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Huron Daily Tribune
  The_Chronicle_of_Philanthropy:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Chronicle of Philanthropy
  WYRK:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WYRK
  KSBY_6:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KSBY 6
  recordonline_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: recordonline.com
  KSAL:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KSAL
  WWBT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WWBT
  WMDT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WMDT
  JG_TC:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: JG-TC
  Radio_Online:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Radio Online
  Ozarks_First:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Ozarks First
  ScreenGeek:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ScreenGeek
  Purdue_University:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Purdue University
  WECT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WECT
  health_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: health.com
  KNSI_Radio:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KNSI Radio
  Just_Jared_Jr_:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Just Jared Jr.
  WVUE_FOX_8_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WVUE FOX 8 News
  ijr_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ijr.com
  VegNews:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: VegNews
  Urban_Milwaukee:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Urban Milwaukee
  KBIA:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KBIA
  Stanford_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Stanford News
  My_MotherLode:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: My MotherLode
  Kiii3_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Kiii3 News
  Americas_Quarterly:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Americas Quarterly
  Fashionista_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Fashionista.com
  WTXL_ABC_27:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WTXL ABC 27
  WCCB:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WCCB
  Design_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Design News
  The_Garden_Island:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Garden Island
  LaughingPlace:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: LaughingPlace
  The_Patriot_Post:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Patriot Post
  New_Canaan_Advertiser:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: New Canaan Advertiser
  Grand_Island_Independent:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Grand Island Independent
  KTNV_Las_Vegas:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KTNV Las Vegas
  WBOC:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WBOC
  KGMI:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KGMI
  The_Clarion_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Clarion News
  Access:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Access
  Baytown_Sun:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Baytown Sun
  INside_INdiana_Business:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: INside INdiana Business
  Middle_East_Eye:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Middle East Eye
  The_Crescent_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Crescent-News
  Bell_of_Lost_Souls:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bell of Lost Souls
  Summit_County:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Summit County
  FOX_10_Phoenix:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FOX 10 Phoenix
  Messenger_Inquirer:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Messenger-Inquirer
  The_Conway_Daily_Sun:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Conway Daily Sun
  Daily_American:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Daily American
  Homeland_Security_Today:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Homeland Security Today
  WBBJ_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WBBJ-TV
  Rigzone:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Rigzone
  The_Paris_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Paris News
  Universal_Hub:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Universal Hub
  Martha_Stewart:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Martha Stewart
  Utah_Public_Radio:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Utah Public Radio
  KPCNews:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KPCNews
  KOB_4:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KOB 4
  WQAD:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WQAD
  AdvisorHub:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AdvisorHub
  GovCon_Wire:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: GovCon Wire
  AVweb:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AVweb
  Link_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Link TV
  emedicinehealth_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: emedicinehealth.com
  The_Fabricator:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Fabricator
  Tiny_House_Talk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Tiny House Talk
  KCTV_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KCTV News
  Bozeman_Daily_Chronicle:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bozeman Daily Chronicle
  Northglenn_Thornton_Sentinel:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Northglenn Thornton Sentinel
  WFLX:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WFLX
  Total_Pro_Sports:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Total Pro Sports
  Missouri_Lawyers_Media:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Missouri Lawyers Media
  WUWM:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WUWM
  KFDI:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KFDI
  www_politico_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: www.politico.com
  WBFO:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WBFO
  Henry_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Henry Herald
  New_York_Giants:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: New York Giants
  travelgumbo_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: travelgumbo.com
  insideHPC:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: insideHPC
  Kane_County_Chronicle:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Kane County Chronicle
  WFMY_News2:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WFMY News2
  Alamogordo_Daily_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Alamogordo Daily News
  East_Oregonian:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: East Oregonian
  wheels24_co_za:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: wheels24.co.za
  WTVY:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WTVY
  The_Post:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Post
  channel24_co_za:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: channel24.co.za
  fin24_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: fin24.com
  sport24_co_za:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: sport24.co.za
  _19_Action_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 19 Action News
  BroBible:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: BroBible
  The_Sydney_Morning_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Sydney Morning Herald
  WFIU:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WFIU
  Mirage_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Mirage News
  WPBF:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WPBF
  SBS:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: SBS
  Business_Insider_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Business Insider Australia
  Brisbane_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Brisbane Times
  The_Canberra_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Canberra Times
  Kalkine_Medi:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Kalkine Medi
  The_New_Daily:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The New Daily
  Ballarat_Courier:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Ballarat Courier
  The_Saturday_Paper:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Saturday Paper
  Pedestrian_TV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Pedestrian TV
  Yahoo_Finance_Australi:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo Finance Australi
  PerthNow:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: PerthNow
  Tasmania_Examiner:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Tasmania Examiner
  Yahoo_Sports:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo Sports
  Illawarra_Mercury:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Illawarra Mercury
  Sunshine_Coast_Daily:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sunshine Coast Daily
  Bendigo_Advertiser:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bendigo Advertiser
  Mamamia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Mamamia
  Green_and_Gold_Rugby:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Green and Gold Rugby
  The_Northern_Daily_Leader:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Northern Daily Leader
  The_Strategis:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Strategis
  Vogue_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Vogue Australia
  FTBL_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FTBL Australia
  Independent_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Independent Australia
  Echonetdaily:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Echonetdaily
  ArtsHub:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ArtsHub
  WAtoday:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WAtoday
  RACGP:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: RACGP
  WiscNews:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: WiscNews
  Motley_Fool_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Motley Fool Australia
  Yahoo_Sport_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo Sport Australia
  Speedcafe:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Speedcafe
  Chronicle:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Chronicle
  Yahoo_News_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo News Australia
  Community_Newspaper_Group:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Community Newspaper Group
  Yahoo_Lifestyle:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo Lifestyle
  _9Honey:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 9Honey
  About_Regional:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: About Regional
  GOPUSA:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: GOPUSA
  The_Roar:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Roar
  KTVB:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: KTVB
  MacroBusines:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: MacroBusines
  CarAdvice:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CarAdvice
  ESP:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ESP
  Parkes_Champion_Post:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Parkes Champion-Post
  ShareCafe:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ShareCafe
  PCMag_A:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: PCMag A
  RenewEconomy:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: RenewEconomy
  My_Sailing:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: My Sailing
  Best_in_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Best in Australia
  New_Idea:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: New Idea
  Honi_Soit:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Honi Soit
  Kotaku_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Kotaku Australia
  Pro_Bono_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Pro Bono Australia
  Gympie_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Gympie Times
  The_World_Game:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The World Game
  Catholic_Leader:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Catholic Leader
  finder_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: finder.com.au
  Australian_Aviation:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Australian Aviation
  The_Big_Smoke_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Big Smoke Australia
  Insurance_Business_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Insurance Business Australia
  Mandurah_Mail:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Mandurah Mail
  Manning_River_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Manning River Times
  Camden_Haven_Courier:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Camden Haven Courier
  Now_To_Love:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Now To Love
  UNSW_Newsroom:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: UNSW Newsroom
  Yahoo_Lifestyle_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo Lifestyle Australia
  Hyundai_A_League:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Hyundai A-League
  Alice_Springs_News_Online:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Alice Springs News Online
  Gloucester_Advocate:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Gloucester Advocate
  East_Asia_Forum:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: East Asia Forum
  The_Maitland_Mercury:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Maitland Mercury
  Forbes_Advocate:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Forbes Advocate
  The_Border_Mail:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Border Mail
  News___The_University_of_Sydne:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: News - The University of Sydne
  Solar_Quote:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Solar Quote
  The_Macleay_Argus:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Macleay Argus
  CSO_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CSO Australia
  Australian_Football_League:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Australian Football League
  Whitsunday_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Whitsunday Times
  Domain_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Domain News
  Lithgow_Mercury:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Lithgow Mercury
  Rask_Media:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Rask Media
  Roy_Morgan_Researc:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Roy Morgan Researc
  The_Music_Network:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Music Network
  Esperance_Express:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Esperance Express
  Daily_Telegraph:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Daily Telegraph
  Queensland_Country_Life:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Queensland Country Life
  Property_Observe:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Property Observe
  Warwick_Daily_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Warwick Daily News
  The_Secto:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Secto
  POPSUGAR_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: POPSUGAR Australia
  Triple_M:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Triple M
  Beat_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Beat Magazine
  Teacher_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Teacher Magazine
  Daily_Examiner:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Daily Examiner
  Western_Advocate:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Western Advocate
  Bega_District_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bega District News
  Wellington_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Wellington Times
  CMC_Markets:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CMC Markets
  South_Burnett_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: South Burnett Times
  Dark_Horizons:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Dark Horizons
  INTHEBLACK:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: INTHEBLACK
  Commercial_Real_Estate_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Commercial Real Estate News
  _9Celebrity:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 9Celebrity
  Good_Food:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Good Food
  Learncfd:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Learncfd
  VICE:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: VICE
  Lifehacker_Australia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Lifehacker Australia
  Cessnock_Advertiser:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Cessnock Advertiser
  Narooma_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Narooma News
  Australasian_Lawyer:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Australasian Lawyer
  Wauchope_Gazette:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Wauchope Gazette
  Newsport:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Newsport
  Architecture_AU:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Architecture AU
  United_News_of_Banglades:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: United News of Banglades
  Daily_News_Gallery:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Daily News Gallery
  National_Post:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: National Post
  The_Financial_Express_BD:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Financial Express BD
  Winnipeg_Free_Press:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Winnipeg Free Press
  The_London_Free_Press:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The London Free Press
  Dhaka_Tribune:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Dhaka Tribune
  The_Motley_Fool_Canada:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Motley Fool Canada
  Canada_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Canada.com
  Technology_Networks:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Technology Networks
  Yahoo_Canada_Finance:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo Canada Finance
  Canada_NewsWir:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Canada NewsWir
  Ottawa_Sun:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Ottawa Sun
  Thorold_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Thorold News
  CanIndia_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CanIndia News
  The_Kingston_Whig_Standard:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Kingston Whig-Standard
  Times_Colonist:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Times Colonist
  paNOW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: paNOW
  The_Journal_Pioneer:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Journal Pioneer
  TSN:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: TSN
  Lethbridge_News_Now:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Lethbridge News Now
  BayToday:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: BayToday
  National_Observer:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: National Observer
  Psychology_Toda:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Psychology Toda
  Yahoo_News_Canada:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Yahoo News Canada
  GuelphToday:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: GuelphToday
  Cape_Breton_Post:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Cape Breton Post
  Prince_George_Citizen:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Prince George Citizen
  CFJC_Today_Kamloops:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CFJC Today Kamloops
  Raptors_Republic:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Raptors Republic
  Net_Newsledger:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Net Newsledger
  The_Sudbury_Star:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Sudbury Star
  Marie_Claire:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Marie Claire
  BarrieToday:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: BarrieToday
  EverythingGP:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: EverythingGP
  Varsity:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Varsity
  Estevan_Mercury:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Estevan Mercury
  Timmins_Press:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Timmins Press
  battlefordsNOW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: battlefordsNOW
  The_North_Bay_Nugget:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The North Bay Nugget
  HuffPost_Canada:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: HuffPost Canada
  Philippine_Canadian_Inquirer:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Philippine Canadian Inquirer
  Vancouver_Is_Awesome:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Vancouver Is Awesome
  Business_in_Vancouver:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Business in Vancouver
  News_UofT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: News@UofT
  Powell_River_Peak:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Powell River Peak
  Driving:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Driving
  Kamloops_This_Week:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Kamloops This Week
  Alberta_Daily_Herald_Tribune:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Alberta Daily Herald Tribune
  Belleville_Intelligencer:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Belleville Intelligencer
  Prince_Albert_Daily_Herald:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Prince Albert Daily Herald
  Thompson_Citizen:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Thompson Citizen
  Monthly_Review:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Monthly Review
  Standard_Freeholder:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Standard Freeholder
  Nanaimo_News_NO:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Nanaimo News NO
  UM_Toda:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: UM Toda
  Sault_Star:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sault Star
  SooToday:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: SooToday
  The_Loo:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Loo
  Western_Hockey_League:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Western Hockey League
  Canadian_Lawyer_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Canadian Lawyer Magazine
  APTN_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: APTN News
  TheBull_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: TheBull.com.au
  Bonnyville_Nouvelle:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bonnyville Nouvelle
  Proactive_Investors_USA___Canada:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Proactive Investors USA & Canada
  Manitoulin_Expositor:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Manitoulin Expositor
  The_Age:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Age
  vogue_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: vogue.com.au
  Owen_Sound_Sun_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Owen Sound Sun Times
  Sporting_News_AU:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sporting News AU
  Toronto_Sta:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Toronto Sta
  Halifax_Examiner:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Halifax Examiner
  North_Shore_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: North Shore News
  Port_Stephens_Examiner:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Port Stephens Examiner
  The_RiotACT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The RiotACT
  News_Mail:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: News Mail
  kawarthaNOW_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kawarthaNOW.com
  NOW_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: NOW Magazine
  _95_7_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 95.7 News
  Cabin_Radio:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Cabin Radio
  UCalgary_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: UCalgary News
  The_Sarnia_Journal:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Sarnia Journal
  Community_Press:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Community Press
  The_Catholic_Register:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Catholic Register
  Brockville_Recorder_and_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Brockville Recorder and Times
  meadowlakeNOW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: meadowlakeNOW
  The_Crag_and_Canyon:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Crag and Canyon
  Gazette:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Gazette
  Dal_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Dal News
  The_Hill_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Hill Times
  The_Organization_for_World_Peac:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Organization for World Peac
  AFT:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AFT
  The_B_C__Catholi:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The B.C. Catholi
  CollingwoodToday:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CollingwoodToday
  Socialist_Project:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Socialist Project
  Chemainus_Valley_Courier:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Chemainus Valley Courier
  The_Post_Millennial:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Post Millennial
  larongeNOW:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: larongeNOW
  CHEK:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CHEK
  The_Gateway_Online:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Gateway Online
  The_Weather_Network:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Weather Network
  Daily_Review:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Daily Review
  University_Affairs:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: University Affairs
  Canadian_Homesteading:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Canadian Homesteading
  Astana_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Astana Times
  InfoTel_News_Ltd:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: InfoTel News Ltd
  Sarnia_Observer:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sarnia Observer
  autoevolution:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: autoevolution
  Vernon_Morning_Star:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Vernon Morning Star
  Coast_Reporter:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Coast Reporter
  Goderich_Signal_Star:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Goderich Signal Star
  CHAT_News_Today:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CHAT News Today
  Clinton_News_Record:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Clinton News Record
  The_Logic:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Logic
  Jamaica_Gleaner:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Jamaica Gleaner
  Sherwood_Park_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sherwood Park News
  Cumberland_News_Now:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Cumberland News Now
  Fernie_Free_Press:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Fernie Free Press
  Radio_Canada_International__en_:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Radio Canada International (en)
  Westerly_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Westerly News
  TimminsToday:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: TimminsToday
  Ubyssey_Online:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Ubyssey Online
